services:
  postgres:
    image: postgres:17.2-alpine
    container_name: portfolio_db
    restart: always
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
