name = "druwan-homepage"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[assets]
binding = "STATIC_ASSETS"

[triggers]
crons = ["0 0 */3 * *"]
